[2025-01-13T23:25:42.655+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:25:42.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:25:42.661+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:25:42.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:25:42.697+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:25:42.693+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:25:42.744+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:25:42.807+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:25:42.807+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:25:42.826+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:25:42.826+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:25:42.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.210 seconds
[2025-01-13T23:26:13.184+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:26:13.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:26:13.188+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:13.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:26:13.220+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:13.219+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:26:13.222+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:26:13.241+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:13.240+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:26:13.251+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:13.251+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:26:13.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.092 seconds
[2025-01-13T23:26:44.302+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:26:44.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:26:44.305+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:44.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:26:44.340+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:44.340+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:26:44.342+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:26:44.358+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:44.358+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:26:44.368+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:26:44.367+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:26:44.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.088 seconds
[2025-01-13T23:27:14.466+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:27:14.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:27:14.480+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:14.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:27:14.507+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:14.506+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:27:14.509+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:27:14.529+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:14.529+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:27:14.539+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:14.539+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:27:14.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.098 seconds
[2025-01-13T23:27:44.866+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:27:44.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:27:44.869+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:44.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:27:44.891+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:44.891+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:27:44.893+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:27:44.907+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:44.907+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:27:44.918+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:27:44.918+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:27:44.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.074 seconds
[2025-01-13T23:28:15.089+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:28:15.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:28:15.093+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:15.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:28:15.116+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:15.115+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:28:15.118+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:28:15.138+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:15.138+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:28:15.149+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:15.149+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:28:15.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.084 seconds
[2025-01-13T23:28:46.180+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:28:46.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:28:46.183+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:46.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:28:46.210+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:46.209+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:28:46.213+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:28:46.231+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:46.231+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:28:46.242+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:28:46.241+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:28:46.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.085 seconds
[2025-01-13T23:29:16.829+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:29:16.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:29:16.833+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:16.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:29:16.872+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:16.872+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:29:16.874+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:29:16.893+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:16.893+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:29:16.903+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:16.903+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:29:16.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.101 seconds
[2025-01-13T23:29:47.336+0000] {processor.py:186} INFO - Started process (PID=579) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:29:47.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:29:47.339+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:47.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:29:47.368+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:47.368+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:29:47.370+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:29:47.389+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:47.389+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:29:47.400+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:29:47.400+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:29:47.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.093 seconds
[2025-01-13T23:30:17.724+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:30:17.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:30:17.727+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:17.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:30:17.762+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:17.761+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:30:17.773+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:30:17.789+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:17.789+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:30:17.801+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:17.800+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:30:17.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.099 seconds
[2025-01-13T23:30:48.538+0000] {processor.py:186} INFO - Started process (PID=707) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:30:48.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:30:48.541+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:48.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:30:48.574+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:48.573+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:30:48.576+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:30:48.594+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:48.594+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:30:48.604+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:30:48.604+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:30:48.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.090 seconds
[2025-01-13T23:31:19.064+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:31:19.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:31:19.067+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:19.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:31:19.098+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:19.097+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:31:19.101+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:31:19.121+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:19.121+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:31:19.132+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:19.132+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:31:19.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.091 seconds
[2025-01-13T23:31:49.456+0000] {processor.py:186} INFO - Started process (PID=834) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:31:49.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:31:49.459+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:49.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:31:49.481+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:49.479+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:31:49.483+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:31:49.502+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:49.502+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:31:49.514+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:31:49.514+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:31:49.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.087 seconds
[2025-01-13T23:32:20.390+0000] {processor.py:186} INFO - Started process (PID=898) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:32:20.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:32:20.393+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:20.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:32:20.420+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:20.419+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:32:20.422+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:32:20.441+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:20.441+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:32:20.451+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:20.450+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:32:20.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.085 seconds
[2025-01-13T23:32:50.992+0000] {processor.py:186} INFO - Started process (PID=962) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:32:50.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:32:50.995+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:50.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:32:51.023+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:51.022+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:32:51.025+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:32:51.044+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:51.043+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:32:51.053+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:32:51.053+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:32:51.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.084 seconds
[2025-01-13T23:33:22.103+0000] {processor.py:186} INFO - Started process (PID=1026) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:33:22.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:33:22.106+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:22.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:33:22.131+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:22.130+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:33:22.133+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:33:22.152+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:22.152+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:33:22.161+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:22.161+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:33:22.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.086 seconds
[2025-01-13T23:33:52.376+0000] {processor.py:186} INFO - Started process (PID=1091) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:33:52.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:33:52.379+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:52.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:33:52.403+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:52.402+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:33:52.405+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:33:52.426+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:52.426+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:33:52.440+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:33:52.440+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:33:52.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.089 seconds
[2025-01-13T23:34:23.215+0000] {processor.py:186} INFO - Started process (PID=1154) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:34:23.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:34:23.219+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:23.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:34:23.250+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:23.249+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:34:23.253+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:34:23.276+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:23.276+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:34:23.292+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:23.292+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:34:23.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.113 seconds
[2025-01-13T23:34:53.610+0000] {processor.py:186} INFO - Started process (PID=1218) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:34:53.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:34:53.615+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:53.614+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:34:53.652+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:53.651+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:34:53.655+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:34:53.677+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:53.677+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:34:53.689+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:34:53.689+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:34:53.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.107 seconds
[2025-01-13T23:35:24.630+0000] {processor.py:186} INFO - Started process (PID=1282) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:35:24.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:35:24.635+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:24.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:35:24.667+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:24.667+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:35:24.670+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:35:24.696+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:24.695+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:35:24.713+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:24.713+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:35:24.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.111 seconds
[2025-01-13T23:35:55.452+0000] {processor.py:186} INFO - Started process (PID=1346) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:35:55.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:35:55.458+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:55.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:35:55.494+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:55.493+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:35:55.496+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:35:55.515+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:55.515+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:35:55.531+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:35:55.530+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:35:55.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.110 seconds
[2025-01-13T23:36:25.607+0000] {processor.py:186} INFO - Started process (PID=1410) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:36:25.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:36:25.611+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:25.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:36:25.644+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:25.643+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:36:25.647+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:36:25.670+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:25.670+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:36:25.686+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:25.686+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:36:25.709+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.109 seconds
[2025-01-13T23:36:56.148+0000] {processor.py:186} INFO - Started process (PID=1474) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:36:56.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:36:56.152+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:56.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:36:56.193+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:56.192+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:36:56.197+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:36:56.220+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:56.220+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:36:56.237+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:36:56.236+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:36:56.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.118 seconds
[2025-01-13T23:37:26.664+0000] {processor.py:186} INFO - Started process (PID=1538) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:37:26.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:37:26.668+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:26.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:37:26.706+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:26.704+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:37:26.709+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:37:26.733+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:26.732+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:37:26.747+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:26.746+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:37:26.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.117 seconds
[2025-01-13T23:37:57.062+0000] {processor.py:186} INFO - Started process (PID=1602) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:37:57.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:37:57.066+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:57.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:37:57.101+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:57.099+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:37:57.104+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:37:57.128+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:57.128+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:37:57.141+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:37:57.141+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:37:57.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.110 seconds
[2025-01-13T23:38:27.695+0000] {processor.py:186} INFO - Started process (PID=1666) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:38:27.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:38:27.701+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:27.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:38:27.730+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:27.728+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:38:27.732+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:38:27.752+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:27.752+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:38:27.766+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:27.766+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:38:27.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.109 seconds
[2025-01-13T23:38:58.558+0000] {processor.py:186} INFO - Started process (PID=1730) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:38:58.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:38:58.561+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:58.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:38:58.576+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:58.575+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:38:58.578+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:38:58.596+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:58.596+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:38:58.608+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:38:58.608+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:38:58.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.074 seconds
[2025-01-13T23:39:28.887+0000] {processor.py:186} INFO - Started process (PID=1794) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:39:28.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:39:28.890+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:28.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:39:28.910+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:28.910+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:39:28.912+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:39:28.930+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:28.930+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:39:28.939+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:28.939+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:39:28.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.081 seconds
[2025-01-13T23:39:59.805+0000] {processor.py:186} INFO - Started process (PID=1858) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:39:59.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:39:59.815+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:59.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:39:59.859+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:59.858+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:39:59.862+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:39:59.892+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:59.892+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:39:59.912+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:39:59.912+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:39:59.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.145 seconds
[2025-01-13T23:40:30.560+0000] {processor.py:186} INFO - Started process (PID=1922) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:40:30.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:40:30.565+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:40:30.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:40:30.599+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:40:30.599+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:40:30.602+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:40:30.621+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:40:30.621+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:40:30.633+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:40:30.633+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:40:30.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.106 seconds
[2025-01-13T23:41:01.202+0000] {processor.py:186} INFO - Started process (PID=1986) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:41:01.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:41:01.205+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:01.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:41:01.237+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:01.236+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:41:01.240+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:41:01.263+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:01.263+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:41:01.277+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:01.277+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:41:01.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.107 seconds
[2025-01-13T23:41:31.381+0000] {processor.py:186} INFO - Started process (PID=2050) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:41:31.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:41:31.385+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:31.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:41:31.418+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:31.417+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:41:31.420+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:41:31.451+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:31.451+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:41:31.466+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:41:31.466+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:41:31.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.114 seconds
[2025-01-13T23:42:01.624+0000] {processor.py:186} INFO - Started process (PID=2115) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:42:01.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:42:01.629+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:01.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:42:01.656+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:01.655+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:42:01.660+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:42:01.689+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:01.689+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:42:01.704+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:01.704+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:42:01.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.111 seconds
[2025-01-13T23:42:32.474+0000] {processor.py:186} INFO - Started process (PID=2178) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:42:32.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:42:32.478+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:32.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:42:32.499+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:32.498+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:42:32.503+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:42:32.521+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:32.521+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:42:32.537+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:42:32.537+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:42:32.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.159 seconds
[2025-01-13T23:43:03.466+0000] {processor.py:186} INFO - Started process (PID=2241) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:43:03.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:43:03.469+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:03.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:43:03.491+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:03.490+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:43:03.493+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:43:03.510+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:03.510+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:43:03.520+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:03.520+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:43:03.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.077 seconds
[2025-01-13T23:43:33.634+0000] {processor.py:186} INFO - Started process (PID=2305) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:43:33.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:43:33.637+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:33.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:43:33.663+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:33.662+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:43:33.666+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:43:33.684+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:33.684+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:43:33.694+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:43:33.694+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:43:33.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.082 seconds
[2025-01-13T23:44:03.974+0000] {processor.py:186} INFO - Started process (PID=2369) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:44:03.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:44:03.977+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:03.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:44:04.004+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:04.003+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:44:04.006+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:44:04.024+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:04.024+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:44:04.034+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:04.034+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:44:04.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.090 seconds
[2025-01-13T23:44:34.383+0000] {processor.py:186} INFO - Started process (PID=2433) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:44:34.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:44:34.387+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:34.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:44:34.415+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:34.414+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:44:34.417+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:44:34.435+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:34.435+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:44:34.449+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:44:34.449+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:44:34.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.089 seconds
[2025-01-13T23:45:04.651+0000] {processor.py:186} INFO - Started process (PID=2496) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:45:04.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:45:04.654+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:04.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:45:04.679+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:04.679+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:45:04.681+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:45:04.699+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:04.699+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:45:04.716+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:04.716+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:45:04.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.088 seconds
[2025-01-13T23:45:34.807+0000] {processor.py:186} INFO - Started process (PID=2560) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:45:34.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:45:34.809+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:34.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:45:34.835+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:34.834+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:45:34.836+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:45:34.853+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:34.853+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:45:34.864+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:45:34.864+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:45:34.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.077 seconds
[2025-01-13T23:46:05.465+0000] {processor.py:186} INFO - Started process (PID=2624) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:46:05.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:46:05.468+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:05.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:46:05.497+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:05.497+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:46:05.500+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:46:05.518+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:05.518+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:46:05.528+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:05.528+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:46:05.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.088 seconds
[2025-01-13T23:46:35.816+0000] {processor.py:186} INFO - Started process (PID=2687) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:46:35.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:46:35.820+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:35.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:46:35.845+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:35.844+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:46:35.847+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:46:35.867+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:35.867+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:46:35.879+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:46:35.879+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:46:35.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.092 seconds
[2025-01-13T23:47:06.515+0000] {processor.py:186} INFO - Started process (PID=2751) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:47:06.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:47:06.518+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:06.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:47:06.546+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:06.545+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:47:06.549+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:47:06.566+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:06.566+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:47:06.576+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:06.576+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:47:06.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.084 seconds
[2025-01-13T23:47:36.853+0000] {processor.py:186} INFO - Started process (PID=2815) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:47:36.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:47:36.857+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:36.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:47:36.885+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:36.885+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:47:36.887+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:47:36.906+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:36.905+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:47:36.916+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:47:36.916+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:47:36.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.102 seconds
[2025-01-13T23:48:07.689+0000] {processor.py:186} INFO - Started process (PID=2879) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:48:07.691+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:48:07.693+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:07.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:48:07.724+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:07.723+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:48:07.727+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:48:07.747+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:07.747+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:48:07.757+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:07.757+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:48:07.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.093 seconds
[2025-01-13T23:48:38.283+0000] {processor.py:186} INFO - Started process (PID=2943) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:48:38.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:48:38.286+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:38.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:48:38.309+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:38.308+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:48:38.311+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:48:38.331+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:38.331+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:48:38.342+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:48:38.342+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:48:38.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.092 seconds
[2025-01-13T23:49:09.177+0000] {processor.py:186} INFO - Started process (PID=3003) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:49:09.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:49:09.182+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:09.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:49:09.218+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:09.217+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:49:09.222+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:49:09.245+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:09.245+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:49:09.258+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:09.258+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:49:09.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.281 seconds
[2025-01-13T23:49:39.641+0000] {processor.py:186} INFO - Started process (PID=3067) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:49:39.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:49:39.645+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:39.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:49:39.671+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:39.670+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:49:39.673+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:49:39.688+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:39.688+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:49:39.698+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:49:39.698+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:49:39.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.077 seconds
[2025-01-13T23:50:10.134+0000] {processor.py:186} INFO - Started process (PID=3126) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:50:10.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:50:10.139+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:10.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:50:10.173+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:10.171+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:50:10.176+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:50:10.199+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:10.199+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:50:10.216+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:10.216+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:50:10.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.115 seconds
[2025-01-13T23:50:41.035+0000] {processor.py:186} INFO - Started process (PID=3185) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:50:41.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:50:41.039+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:41.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:50:41.074+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:41.072+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:50:41.077+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:50:41.104+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:41.104+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:50:41.118+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:50:41.118+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:50:41.142+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.112 seconds
[2025-01-13T23:51:11.342+0000] {processor.py:186} INFO - Started process (PID=3247) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:51:11.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:51:11.346+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:11.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:51:11.373+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:11.372+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:51:11.375+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:51:11.392+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:11.391+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:51:11.402+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:11.402+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:51:11.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.079 seconds
[2025-01-13T23:51:41.487+0000] {processor.py:186} INFO - Started process (PID=3308) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:51:41.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:51:41.490+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:41.490+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:51:41.511+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:41.510+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:51:41.514+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:51:41.535+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:41.535+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:51:41.550+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:51:41.550+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:51:41.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.091 seconds
[2025-01-13T23:52:11.893+0000] {processor.py:186} INFO - Started process (PID=3372) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:52:11.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:52:11.896+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:11.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:52:11.926+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:11.925+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:52:11.930+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:52:11.954+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:11.954+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:52:11.968+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:11.967+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:52:11.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.095 seconds
[2025-01-13T23:52:42.668+0000] {processor.py:186} INFO - Started process (PID=3436) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:52:42.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:52:42.671+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:42.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:52:42.691+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:42.690+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:52:42.693+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:52:42.715+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:42.714+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:52:42.726+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:52:42.726+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:52:42.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.088 seconds
[2025-01-13T23:53:13.169+0000] {processor.py:186} INFO - Started process (PID=3500) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:53:13.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:53:13.172+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:13.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:53:13.203+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:13.202+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:53:13.206+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:53:13.225+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:13.224+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:53:13.237+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:13.237+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:53:13.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.094 seconds
[2025-01-13T23:53:43.708+0000] {processor.py:186} INFO - Started process (PID=3564) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:53:43.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:53:43.712+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:43.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:53:43.740+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:43.739+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:53:43.742+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:53:43.762+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:43.762+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:53:43.775+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:53:43.774+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:53:43.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.091 seconds
[2025-01-13T23:54:14.370+0000] {processor.py:186} INFO - Started process (PID=3628) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:54:14.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:54:14.374+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:14.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:54:14.401+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:14.400+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:54:14.403+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:54:14.428+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:14.427+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:54:14.443+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:14.443+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:54:14.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.104 seconds
[2025-01-13T23:54:44.863+0000] {processor.py:186} INFO - Started process (PID=3692) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:54:44.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:54:44.867+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:44.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:54:44.901+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:44.900+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:54:44.903+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:54:44.922+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:44.921+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:54:44.934+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:54:44.934+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:54:44.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.100 seconds
[2025-01-13T23:55:15.524+0000] {processor.py:186} INFO - Started process (PID=3757) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:55:15.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:55:15.527+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:15.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:55:15.562+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:15.561+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:55:15.565+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:55:15.589+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:15.588+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:55:15.600+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:15.599+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:55:15.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.102 seconds
[2025-01-13T23:55:46.233+0000] {processor.py:186} INFO - Started process (PID=3821) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:55:46.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:55:46.236+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:46.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:55:46.271+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:46.270+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:55:46.273+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:55:46.296+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:46.295+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:55:46.307+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:55:46.306+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:55:46.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.099 seconds
[2025-01-13T23:56:16.926+0000] {processor.py:186} INFO - Started process (PID=3885) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:56:16.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:56:16.931+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:16.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:56:16.963+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:16.962+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:56:16.966+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:56:16.989+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:16.988+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:56:17.003+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:17.003+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:56:17.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.110 seconds
[2025-01-13T23:56:47.882+0000] {processor.py:186} INFO - Started process (PID=3949) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:56:47.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:56:47.887+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:47.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:56:47.919+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:47.918+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:56:47.922+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:56:47.947+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:47.947+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:56:47.967+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:56:47.967+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:56:47.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.121 seconds
[2025-01-13T23:57:18.464+0000] {processor.py:186} INFO - Started process (PID=4013) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:57:18.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:57:18.468+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:18.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:57:18.499+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:18.497+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:57:18.502+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:57:18.525+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:18.524+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:57:18.544+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:18.544+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:57:18.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.113 seconds
[2025-01-13T23:57:49.136+0000] {processor.py:186} INFO - Started process (PID=4077) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:57:49.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:57:49.141+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:49.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:57:49.178+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:49.177+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:57:49.182+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:57:49.208+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:49.208+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:57:49.220+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:57:49.220+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:57:49.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.109 seconds
[2025-01-13T23:58:19.597+0000] {processor.py:186} INFO - Started process (PID=4141) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:58:19.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:58:19.601+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:19.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:58:19.637+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:19.636+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:58:19.639+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:58:19.667+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:19.667+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:58:19.681+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:19.680+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:58:19.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.114 seconds
[2025-01-13T23:58:50.583+0000] {processor.py:186} INFO - Started process (PID=4210) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:58:50.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:58:50.587+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:50.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:58:50.622+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:50.621+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:58:50.628+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:58:50.648+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:50.648+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:58:50.660+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:58:50.660+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:58:50.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.104 seconds
[2025-01-13T23:59:20.997+0000] {processor.py:186} INFO - Started process (PID=4274) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:59:20.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:59:21.002+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:21.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:59:21.044+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:21.043+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:59:21.047+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:59:21.074+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:21.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:59:21.091+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:21.090+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:59:21.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.128 seconds
[2025-01-13T23:59:51.211+0000] {processor.py:186} INFO - Started process (PID=4337) to work on /opt/airflow/dags/ETLproject.py
[2025-01-13T23:59:51.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETLproject.py for tasks to queue
[2025-01-13T23:59:51.215+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:51.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:59:51.252+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:51.251+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2025-01-13T23:59:51.254+0000] {processor.py:925} INFO - DAG(s) 'DAG_Project_CF' retrieved from /opt/airflow/dags/ETLproject.py
[2025-01-13T23:59:51.276+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:51.276+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-13T23:59:51.289+0000] {logging_mixin.py:190} INFO - [2025-01-13T23:59:51.287+0000] {dag.py:4180} INFO - Setting next_dagrun for DAG_Project_CF to None, run_after=None
[2025-01-13T23:59:51.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETLproject.py took 0.122 seconds
